package com.danielbporter.nyctrips;

import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
@EnableBatchProcessing
public class App {



    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
//        runJob();
    }

//    private void runJob() throws JobParametersInvalidException, JobExecutionAlreadyRunningException, JobRestartException, JobInstanceAlreadyCompleteException {
//        JobExecution exec = jobLauncher.run(yellowTripFeeder, null);
//        System.out.println("exec: " + exec);
//    }

}
